# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - object-storage-xrd.yaml
  - s3-us-west-2.yaml
