apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cloudwatch-metrics-write.yaml
- firehose-write.yaml
- definition.yaml
- dynamodb-write.yaml
- kms-read.yaml
- lambda-invoke.yaml
- s3-read.yaml
- s3-write.yaml
- s3-write-firehose.yaml
- sqs-read.yaml
- sqs-write.yaml
